const TOKEN_JWT_EXPIRES = 60 * 60;
const DEFAULT_LIMIT = 20;
const DEFAULT_OFFSET = 0;
const DEFAULT_LENGTH_WEET = 40;
const USER_ROLE = {
  ADMIN: 'admin',
  REGULAR: 'regular'
};

module.exports = {
  TOKEN_JWT_EXPIRES,
  DEFAULT_LIMIT,
  DEFAULT_OFFSET,
  USER_ROLE,
  DEFAULT_LENGTH_WEET
};
